table f_Order_items
	lineageTag: dc305480-ea06-41ea-a14b-d16edfe9b43d

	column order_id
		dataType: string
		lineageTag: 5f118c3b-d525-41e4-8616-3a5d716a18d0
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 7c92a944-db50-4268-98af-b7d683f64309
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: d25f61cb-ed06-4a25-881b-76fbe270de9b
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column order_item_id
		dataType: int64
		formatString: 0
		lineageTag: fafe6268-d1e7-4191-82d4-186882c6b8aa
		summarizeBy: sum
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column shipping_limit_ts
		dataType: dateTime
		formatString: General Date
		lineageTag: 91441086-0e59-49bc-b4a2-efc91c9a3ede
		summarizeBy: none
		sourceColumn: shipping_limit_ts

		variation Variation
			isDefault
			relationship: 18766847-687e-49c8-8a85-abb1befa747b
			defaultHierarchy: LocalDateTable_6e3ef1d7-d76e-4150-9d21-76afbfc0937d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column is_free_shipping
		dataType: int64
		formatString: 0
		lineageTag: 775e2b9a-a451-44c5-b33a-0ec536151246
		summarizeBy: sum
		sourceColumn: is_free_shipping

		annotation SummarizationSetBy = Automatic

	column item_price
		dataType: double
		lineageTag: 3a935f73-4538-47d1-bc84-4396c6d824b9
		summarizeBy: sum
		sourceColumn: item_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column item_freight_value
		dataType: double
		lineageTag: 7fc8eb2b-3893-4fb3-b9ed-3a629baeed78
		summarizeBy: sum
		sourceColumn: item_freight_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column item_gross_revenue
		dataType: double
		lineageTag: 7d10668c-1a79-48fa-b7a1-473fc95fe3d4
		summarizeBy: sum
		sourceColumn: item_gross_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition f_Order_items = m
		mode: import
		source =
				let
				    Source = Sql.Database(mysv, mydb),
				    gold_fact_order_items = Source{[Schema="gold",Item="fact_order_items"]}[Data],
				    #"Reordered Columns" = Table.ReorderColumns(gold_fact_order_items,{"order_id", "product_id", "seller_id", "order_item_id", "shipping_limit_ts", "is_free_shipping", "item_price", "item_freight_value", "item_gross_revenue"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

